version: "3.8"

services:
  jira:
    image: atlassian/jira-software:9.15.0
    ports:
      - "9090:8080"
    volumes:
      - jiraVolume:/var/atlassian/application-data/jira
    environment:
      ATLASSIAN_JIRA_HOME: /var/atlassian/application-data/jira
    container_name: jira

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jiraVolume:
  jenkins_home:
