Feature: MMPI-T3381-TC04-Error validation for Personal details step of Enrolment component in MAM tenant
    @TestCaseKey=TAT-T49
        
        Scenario Outline:Error validation for Personal details step of Enrolment component in MAM tenant
            Given user is in the TravelID Enrolment page in MAM
            And user enters the "emailaddress@yopmail.com" and "Test@1234" in the Registration Step
            And user enters '<First Name>''<Last Name>''<DOB DD-MM-YYYY>''<Country>''<street>''<postcode>''<city>''<Telephone number (Prefix, Area code, NO>' in the respective fields
            When user clicks continue
            Then '<First Name error>''<Last Name Error>''<DOB Error>''<Country Error>''<Street Error>''<Postcode Error>''<City Error>''<Telephone Error>' errors texts are displayed below the respective fields with invalid data
        
            Examples:
              | First Name       | First Name error                                            | Last Name | Last Name Error                                       | DOB DD-MM-YYYY | DOB Error                                                                     | Country     | Country Error                                                     | street | Street Error                                                | postcode | Postcode Error                                        | city   | City Error                                                 | Telephone number (Prefix, Area code, NO | Telephone Error                                                     |
              | Test@            | The first name contains invalid characters.                 | Test@     | The surname contains invalid characters.              | 33-33-1997     | The date of birth is invalid.                                                 | Germany (DE) |                                                                   | Test@  | Only letters, numbers, “/” and “-” are permitted.           | hshse     | Please enter your postcode using the official format. | Test@1 | The city field contains invalid characters.                | +49, , 1234555                          | This is a mandatory field. Please enter your area code.             |
              | TestNameLastName | A max. 15 characters are permitted for each first name.     | Test Name |                                                       | 10-10-2025     | The minimum age for registering with the Miles & More programme is two years. | Germany (DE) |                                                                   | Test 1 |                                                             | 64200    |                                                       | Test   |                                                            | +49, 123,                               | This is a mandatory field. Please enter your telephone number here. |
              |                  | This is a mandatory field. Please enter your first name(s). |           | This is a mandatory field. Please enter your surname. | - - -          | These are mandatory fields. Please enter your date of birth.                  |             | This is a mandatory field. Please choose your place of residence. |        | Please enter your street and house number or PO Box number. |          | Please enter your postcode.                           |        | This is a mandatory field. Please enter your town or city. | +49, , ,                                 | This is a mandatory field. Please enter your area code. |