Feature: MMPI-T3380-TC03_Error validation for Registration step of Enrolment component in MAM tenant
    @TestCaseKey=TAT-T48
        
        Scenario Outline: Validate error messages and recovery scenarios during Travel ID Enrolment
          Given user is in "<tenant>" page
          And user enters email as "<email>" and password as "<password>" in the Registration Step
          When user clicks Continue button
          Then error is displayed as "<emailerror>" and "<passworderror>" if applicable
          And if activation is expired, user clicks on Start Registration Again and retries registration
          Then user is able to navigate to personal details if applicable
        
        Examples:
          | tenant | email                   | password  | emailerror                                                                                     | passworderror               |
          | https://account-uat1.miles-and-more.com/web/de/en/enrolment.html?client_id=vjLGLNf95WRAvFsZ0aJTfa4qgpTHSL98&principal_type=SERVICE_CARD_NUMBER&redirect_uri=https%3A%2F%2Fwww-uat1.miles-and-more.com&reduced_state=NONE&response_type=code&scope=AUTHENTICATED+IDENTIFIED+urn%3Amilesandmore%3Atech%3Abackground%3Av1%3Aactive&state=MjI5NzMxODEyMDYxOTYxOTQ5MTE1Mjc4MTcxNzExODYzOTE5ODExOTU | Test@                   | Test     | Please enter your email address in the following format: email@address.com                     | The password is invalid.    |
          | https://account-uat1.miles-and-more.com/web/de/en/enrolment.html?client_id=vjLGLNf95WRAvFsZ0aJTfa4qgpTHSL98&principal_type=SERVICE_CARD_NUMBER&redirect_uri=https%3A%2F%2Fwww-uat1.miles-and-more.com&reduced_state=NONE&response_type=code&scope=AUTHENTICATED+IDENTIFIED+urn%3Amilesandmore%3Atech%3Abackground%3Av1%3Aactive&state=MjI5NzMxODEyMDYxOTYxOTQ5MTE1Mjc4MTcxNzExODYzOTE5ODExOTU |                         |          | Please enter your email address.                                                               | Please enter your password. |
          | https://account-uat1.miles-and-more.com/web/de/en/enrolment.html?client_id=vjLGLNf95WRAvFsZ0aJTfa4qgpTHSL98&principal_type=SERVICE_CARD_NUMBER&redirect_uri=https%3A%2F%2Fwww-uat1.miles-and-more.com&reduced_state=NONE&response_type=code&scope=AUTHENTICATED+IDENTIFIED+urn%3Amilesandmore%3Atech%3Abackground%3Av1%3Aactive&state=MjI5NzMxODEyMDYxOTYxOTQ5MTE1Mjc4MTcxNzExODYzOTE5ODExOTU | mmgt.oneid2@yopmail.com | Test@123 | An account with this email address already exists. Please use another email address or log in. |                              |
          | https://account-uat1.miles-and-more.com/web/de/en/enrolment.html?client_id=vjLGLNf95WRAvFsZ0aJTfa4qgpTHSL98&principal_type=SERVICE_CARD_NUMBER&redirect_uri=https%3A%2F%2Fwww-uat1.miles-and-more.com&reduced_state=NONE&response_type=code&scope=AUTHENTICATED+IDENTIFIED+urn%3Amilesandmore%3Atech%3Abackground%3Av1%3Aactive&state=MjI5NzMxODEyMDYxOTYxOTQ5MTE1Mjc4MTcxNzExODYzOTE5ODExOTU | Yxtkqibmxs@yopmail.com  | Test@1234| An account with this email address already exists. Please use another email address or log in. |                              |
          | https://account-uat1.miles-and-more.com/web/de/en/enrolment/enrolment-completion.html?client_id=vjLGLNf95WRAvFsZ0aJTfa4qgpTHSL98&redirect_uri=https%3A%2F%2Fwww-uat1.miles-and-more.com&scope=AUTHENTICATED+IDENTIFIED+urn%3Amilesandmore%3Atech%3Abackground%3Av1%3Aactive&state=MTA2MjUwMTUzNjAyNTQ4MzUxNDExODEyMjgyMDE1MTQwMjE1MTI5MTc1&principal_type=SERVICE_CARD_NUMBER&eto=46d5f0fe-0049-11ee-bb34-0a580a010e29&cld=0               | Sdkcajtjgf@yopmail.com   | Test@1234|                                                                                                  |                              |